# fly.toml app configuration file generated for schedulur on 2025-04-26T15:36:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'schedulur'
primary_region = 'sjc'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
